apiVersion: v1
kind: Service
metadata:
  name: ga4-prometheus-exporter
  labels:
    app.kubernetes.io/name: ga4-prometheus-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9674"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9674
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: ga4-prometheus-exporter
